export const PORTAL_CONFIG = {
  ADAPTER_TIMEOUT_MS: parseInt(process.env.PORTAL_ADAPTER_TIMEOUT_MS || "15000", 10),
  AGGREGATE_TIMEOUT_MS: parseInt(process.env.PORTAL_AGGREGATE_TIMEOUT_MS || "30000", 10),
  MAX_ADAPTER_CONCURRENCY: parseInt(process.env.PORTAL_MAX_CONCURRENCY || "4", 10),
  DEFAULT_PAGE_SIZE: 10,
  CACHE_TTL_SECONDS: parseInt(process.env.PORTAL_CACHE_TTL_SECONDS || "600", 10),
  CIRCUIT_BREAKER_FAILURES: 3,
  CIRCUIT_BREAKER_RESET_MS: 60000,
  RETRY_MAX_ATTEMPTS: 2,
  RETRY_INITIAL_DELAY_MS: 200,
};
